SoccerManager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="SoccerManager API",
      default_version='v1',
      description="This is an OpenApi documentation for SoccerManager.",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="prms.regmi@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('home.urls')),
    path('api/v1/', include('home.api_urls')),
]

home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # API URLS ONLY
    path('', team_page, name="team_page"),
    path('transfer_list/', transfer_list, name="transfer_list"),
    path('logout/', views_logout, name="views_logout")


    
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django_countries.fields import CountryField
import random

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, name=None):

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, name):
        
        user = self.create_user(
            email=email,
            password=password,
            name=name,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user
        
class CustomUser(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length = 25)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

    def has_perm(self, perm, obj = None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    def __str__(self):
        return self.name +" => "+ self.email + " (Active: " + str(self.active) + ")"

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin
    
    @property
    def is_active(self):
        return self.active

class Team(models.Model):
    name = models.CharField(max_length = 50)
    country = models.CharField(max_length = 50, default="")
    in_the_bank = models.IntegerField(default = 5000000)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, null=True, blank=True)

def random_age():
    return random.randint(18, 40)

class Player(models.Model):
    position = ('goalkeeper', 'goalkeeper'), ('midfielder', 'midfielder'), ('defender', 'defender'), ('attacker', 'attacker')
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    player_position = models.CharField(choices = position, max_length = 15)
    country = models.CharField(max_length = 50, default="")
    age = models.IntegerField(default = random_age)
    market_value = models.IntegerField(default = 1000000)
    team = models.ForeignKey(Team, blank = True, null = True, on_delete=models.PROTECT)
    in_transfer = models.BooleanField(default = False)
    asking_price = models.IntegerField(default = 0)

home/views.py
from socket import timeout
from django.shortcuts import render, redirect
import requests
from rest_framework.authtoken.models import Token
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required

def get_url(request):
    return request.scheme + "://" + request.get_host()

def team_page(request):
    try:
        token = Token.objects.get_or_create(user=request.user)[0].key
        headers = {"Authorization":"Token "+ token}
    except:
        headers = {"Authorization":None}

    context = {}
    url = get_url(request) + "/api/v1/team_page"
    r = requests.get(url = url, headers=headers, timeout=10)
    if(r.status_code == 200):
        context['team'] = r.json()
    else:
        context['error'] = r.content.decode("utf-8")
    
    if request.method == "POST":
        url = get_url(request) + "/api/v1/transfer_player/" + request.POST.get("transfer-btn") +"/"
        print(url)
        data = {
            "asking_price":  request.POST.get("asking-price"),
        }
        r = requests.patch(url = url, data = data, headers = headers, timeout=10)
        if(r.status_code == 200):
            context['message'] = "Transfer Successful"
            return redirect('team_page')

        else:
            context['message'] = r.content.decode("utf-8")

    return render(request, "team_page.html", context)


def transfer_list(request):
    try:
        token = Token.objects.get_or_create(user=request.user)[0].key
        headers = {"Authorization":"Token "+ token}
    except:
        headers = {"Authorization":None}

    context = {}
    url = get_url(request) + "/api/v1/transfer_list"
    r = requests.get(url = url, headers=headers, timeout=10)
    if(r.status_code == 200):
        context['transfer_list'] = r.json()
    else:
        context['message'] = r.content.decode("utf-8")
    
    if request.method == "POST":
        url = get_url(request) + "/api/v1/purchase_player/" + request.POST.get("buy-btn") +"/"
        r = requests.patch(url = url, headers = headers, timeout=10)
        if(r.status_code == 200):
            context['message'] = "Purchase Successful"
            return redirect('transfer_list')

        else:
            context['message'] = r.content.decode("utf-8")

    return render(request, "transfer_list.html", context)

def views_logout(request):
    auth_logout(request)
    return redirect("/swagger/")
    

templates/team_page.html
<!DOCTYPE html>
<html>
<head>
    {%load static%}
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Team Page</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background: url('{%static 'bg.jpg' %}') no-repeat center center fixed;">
    <div class="container mt-3" style="color: #fff;">
        
        {%if message%}
        <alert class="alert-danger">
            {{message}}
        </alert>
        {%endif%}
        <div class="row">
            <div class="col-6">
                
                <h2>{{team.name}}</h2>
                <h4>{{team.country}}</h4>
            </div>
            <div class="col-2">
                <h5><a href="{%url 'transfer_list' %}" style="color: #fff;">View Transfer List</a></h5>
                <a href="{% url 'views_logout' %}" style="color: #fff;">Logout</a>
            </div>
            <div class="col-4 text-right">
                <h3><sup><small>In the Bank (Budget) </small></sup>{{team.in_the_bank}}</h3>
                <h3><sup><small>Team Value </small></sup>{{team.team_value}}</h3>
            </div>
            <div class="col-12">
                <div class="row">
                {%for p in team.players%}
                <div class="col-4 my-2">
                    <div class="py-2" style="background-color: rgba(0,0,0,0.5); border-radius: 5px;">
                    <div class="row">
                        <div class="col-auto px-0 text-center">
                            <img src="{%static 'player.png' %}" style="height: 120px;">
                        </div>
                        <div class="col">
                            {%if not p.in_transfer%}
                                <button class="btn btn-outline-light btn-sm py-1" style="position: absolute; right: 22px;" onclick="transfer_button_click('{{p.id}}');">Transfer
                                </button>
                            {%endif%}
                            ID: <strong>{{p.id}}</strong><br>
                            <b>{{p.last_name}}, </b>{{p.first_name}}<br>
                            $ {{p.market_value}}<br>
                            {{p.player_position}}, {{p.country}}<br>
                            Age: {{p.age}}
                        </div>
                    </div>
                    
                    {%if p.in_transfer%}
                    <img src="{%static 'transfer.png' %}" style="height: 25px; position: absolute; bottom: 15px; right: 30px;">
                    {%endif%}
                    </div>
                </div>
                {%endfor%}
                </div>

            </div>
        </div>
        
    </div>
    
    <div class="modal fade" id="tranfer_player_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Tranfer Player</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col">
                            <input type="number" name="asking-price" class="form-control" placeholder="Asking Price in Dollars ($)">
                        </div>
                        <div class="col-auto">
                            <button type="submit" id="transfer-btn" name="transfer-btn" class="btn btn-primary">Transfer</button>
                        </div>
                    </div>
                </form>
            </div>
          </div>
        </div>
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script type="text/javascript">
        function transfer_button_click(id){
            $('#transfer-btn').val(id);
            $('#tranfer_player_modal').modal('show');
        }
      </script>
</body>
</html>

templates/transfer_list.html
<!DOCTYPE html>
<html>
<head>
    {%load static%}
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Team Page</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background: url('{%static 'bg.jpg' %}') no-repeat center center fixed;">
    <div class="container mt-3" style="color: #fff;">
        <div class="row">
            <div class="col-8">
                <h2>Transfer List</h2>
            </div>
            <div class="col-4 text-right">
                <h5><a href="{%url 'team_page' %}" style="color: #fff;">View My Team</a></h5>
            </div>
        </div>
        {%if message%}
        <alert class="alert-danger">
            {{message}}
        </alert>
        {%endif%}
        <div class="row">
        {%for p in transfer_list%}
        <div class="col-4 my-2">
            <div class="py-2" style="background-color: rgba(0,0,0,0.5); border-radius: 5px; {%if p.team.id == request.user.team_set.all.0.id %}border-left: 3px solid red;{%endif%}">
            <div class="row">
                <div class="col-auto px-0 text-center">
                    <img src="{%static 'player.png' %}" style="height: 120px;"><br>
                    ID: <strong>{{p.id}}</strong>
                </div>
                <div class="col">
                    {%if not p.team.id == request.user.team_set.all.0.id %}
                    <form method="POST">
                        {%csrf_token%}
                    <button class="btn btn-outline-light btn-sm py-1" style="position: absolute; right: 22px;" value="{{p.id}}" name="buy-btn">
                        Buy
                    </button>
                    </form>
                    {%endif%}
                    <b>{{p.last_name}}, </b>{{p.first_name}}<br>
                    Value $ {{p.market_value}}<br>
                    Asking Price $ {{p.asking_price}}<br>
                    {{p.player_position}}, {{p.country}} <br>
                    Team: {{p.team.name}}<br>
                    Age: {{p.age}}
                    
                </div>
            </div>
            {%if p.in_transfer%}
            <img src="{%static 'transfer.png' %}" style="height: 25px; position: absolute; bottom: 15px; right: 30px;">
            {%endif%}
            </div>
        </div>
        {%endfor%}
        </div>
    </div>
</body>
</html>